/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["job_status_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Job
         * @description Deletes a batch from every store.
         *
         *     All three or none. Deleting SQL rows but leaving vectors behind produces
         *     orphan chunks that keep surfacing as evidence for a candidate the system
         *     claims not to have -- which is both a bug and, for personal data, a
         *     compliance failure.
         */
        delete: operations["delete_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rank */
        post: operations["rank_api_rank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Audit
         * @description Runs the ranking, then audits the resulting shortlist for disparate impact.
         */
        post: operations["audit_api_audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttributeAuditResponse */
        AttributeAuditResponse: {
            /** Attribute */
            attribute: string;
            /** Description */
            description: string;
            /** Impact Ratio */
            impact_ratio?: number | null;
            /** Flagged */
            flagged: boolean;
            /** Groups */
            groups: components["schemas"]["GroupStat"][];
        };
        /** AuditResponse */
        AuditResponse: {
            /** Job Id */
            job_id: string;
            /** Shortlist Size */
            shortlist_size: number;
            /** Total Candidates */
            total_candidates: number;
            /** Attributes */
            attributes: components["schemas"]["AttributeAuditResponse"][];
            /** Note */
            note: string;
        };
        /** Body_upload_api_upload_post */
        Body_upload_api_upload_post: {
            /**
             * File
             * @description A .zip of .pdf and .docx resumes
             */
            file: string;
            /** Job Id */
            job_id?: string | null;
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Requirement */
            requirement: string;
            /** Weight */
            weight: number;
            /** Score */
            score: number;
            /**
             * Source
             * @enum {string}
             */
            source: "database" | "retrieval" | "missing";
            /** Quote */
            quote?: string | null;
        };
        /** FileReport */
        FileReport: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Resume Id */
            resume_id?: string | null;
            /**
             * N Chunks
             * @default 0
             */
            n_chunks: number;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** GroupStat */
        GroupStat: {
            /** Value */
            value: string;
            /** Total */
            total: number;
            /** Selected */
            selected: number;
            /** Selection Rate */
            selection_rate: number;
            /** Reliable */
            reliable: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobStatus */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "ingesting" | "extracting" | "indexing" | "ready" | "failed";
            /**
             * Stage Message
             * @default
             */
            stage_message: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * N Files
             * @default 0
             */
            n_files: number;
            /**
             * N Parsed
             * @default 0
             */
            n_parsed: number;
            /**
             * N Chunks
             * @default 0
             */
            n_chunks: number;
            /**
             * N Candidates
             * @default 0
             */
            n_candidates: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Error */
            error?: string | null;
            /** Files */
            files?: components["schemas"]["FileReport"][];
        };
        /** ParsedRequirement */
        ParsedRequirement: {
            /** Text */
            text: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "hard" | "soft";
            /** Weight */
            weight: number;
            /** Skill */
            skill?: string | null;
            /** Min Years */
            min_years?: number | null;
            /** Degree Level */
            degree_level?: string | null;
        };
        /** RankRequest */
        RankRequest: {
            /**
             * Job Id
             * @description The upload batch to rank within.
             */
            job_id: string;
            /**
             * Jd Text
             * @description The job description, as text.
             */
            jd_text: string;
            /**
             * Shortlist Size
             * @default 45
             */
            shortlist_size: number;
            /**
             * Include Excluded
             * @description Return candidates removed by hard requirements, with the reason. Recommended: a filter that silently deletes people is how a broken requirement goes unnoticed.
             * @default true
             */
            include_excluded: boolean;
        };
        /** RankResponse */
        RankResponse: {
            /** Job Id */
            job_id: string;
            /** Title */
            title?: string | null;
            /** Requirements */
            requirements: components["schemas"]["ParsedRequirement"][];
            /** Filter Spec */
            filter_spec: {
                [key: string]: unknown;
            };
            /** Total Candidates */
            total_candidates: number;
            /** Passed Filter */
            passed_filter: number;
            /** Shortlist */
            shortlist: components["schemas"]["RankedCandidate"][];
            /** Excluded */
            excluded?: components["schemas"]["RankedCandidate"][];
            /** Seconds */
            seconds: number;
        };
        /** RankedCandidate */
        RankedCandidate: {
            /** Rank */
            rank?: number | null;
            /** Resume Id */
            resume_id: string;
            /** Name */
            name: string;
            /** Headline */
            headline?: string | null;
            /** Years */
            years: number;
            /** Highest Degree */
            highest_degree: string;
            /** Score */
            score: number;
            /** Requirements Met */
            requirements_met: number;
            /** Requirements Total */
            requirements_total: number;
            /** Passed Filter */
            passed_filter: boolean;
            /** Exclusion Reasons */
            exclusion_reasons?: string[];
            /** Evidence */
            evidence?: components["schemas"]["EvidenceItem"][];
        };
        /** UploadResponse */
        UploadResponse: {
            /** Job Id */
            job_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "ingesting" | "extracting" | "indexing" | "ready" | "failed";
            /** Message */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upload_api_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"][];
                };
            };
        };
    };
    job_status_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rank_api_rank_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
